// The portfolio's project catalog. Add new work here, then run npm run build.
export const projects = [
  {
    id: 'dino-browser',
    title: 'Dino Defense',
    edition: 'Browser',
    category: 'games',
    type: 'Tower defense',
    platform: 'Browser game',
    color: '#d2b77b',
    headline: 'Tower defense.\nPrehistoric chaos.',
    description:
      'A dinosaur tower defense game. Build and upgrade your weapons, hold the line, and survive one more wave.',
    url: 'https://vibecodingmatt.github.io/dino-defense/',
    source: 'https://github.com/vibecodingmatt/dino-defense',
    action: 'Play the game',
    preview: 'assets/previews/dino-browser-v2.webm',
    image: 'assets/images/dino-browser-wide.webp',
    thumbnail: 'assets/images/dino-browser-card.webp',
    alt: 'Dino Defense artwork: a T. rex breaks through a sparking jungle fence.',
    imageLabel: 'Project artwork',
    previewLabel: 'Defense in action · 16s',
    tags: ['JavaScript', 'Canvas', 'Game systems'],
    facts: [
      ['7', 'island zones'],
      ['33', 'dinosaurs'],
      ['100', 'waves per zone'],
    ],
    hook: 'A dinosaur tower defense game built around the irresistible promise of one more wave.',
    challenge:
      'Make deep tower defense feel immediate: readable threats, meaningful upgrades, and a reason to return after a run ends.',
    craft:
      'Wave progression, distinct dinosaur behaviors, weapon upgrades, and permanent DNA research work together. Responsive controls and portable saves let the experience travel between desktop and phone.',
    notice: 'Artwork introduces the world; the preview shows the actual browser game.',
  },
  {
    id: 'dino-roblox',
    title: 'Dino Defense',
    edition: 'Roblox',
    category: 'games',
    type: '3D tower defense',
    platform: 'Roblox experience',
    color: '#edbd60',
    headline: 'Tower defense.\nFrom the front line.',
    description:
      'A 3D tower defense game on Roblox. Team up, build your defenses, and face dinosaur waves from inside the action.',
    url: 'https://www.roblox.com/games/98883356694296/Dino-Defense',
    source: null,
    action: 'Play on Roblox',
    preview: null,
    image: 'assets/images/dino-roblox-wide.webp',
    thumbnail: 'assets/images/dino-roblox-card.webp',
    alt: 'Dino Defense Roblox artwork with a block-built T. rex, jungle gates, and rocket defenses.',
    imageLabel: 'Project artwork',
    previewLabel: 'Project artwork',
    tags: ['Luau', 'Roblox Studio', 'Blender'],
    facts: [
      ['3D', 'island world'],
      ['Co-op', 'shared defense'],
      ['Luau', 'gameplay systems'],
    ],
    hook: 'Cooperative tower defense, rebuilt as a world you can stand inside.',
    challenge:
      'Translate a browser tower defense game into an embodied, shared experience with readable placement, responsive combat, and a strong sense of scale.',
    craft:
      'A filesystem-first Luau project brings together procedural environments, shared rewards, upgradeable defenses, and custom creature work. The browser and Roblox editions develop as distinct experiences.',
    notice:
      'Open the experience on Roblox to play. The Roblox app is required. This showcase uses the project’s promotional artwork.',
  },
  {
    id: 'war-survival',
    title: 'War: Survival',
    edition: '',
    category: 'games',
    type: 'Squad survival',
    platform: 'Browser game',
    color: '#ff895f',
    headline: 'A small squad.\nAn impossible world.',
    description:
      'Recruit. Upgrade. Hold the line. Lead a growing squad through fifteen worlds that refuse to play fair.',
    url: 'https://vibecodingmatt.github.io/war-survival/',
    source: 'https://github.com/vibecodingmatt/war-survival',
    action: 'Play the game',
    preview: 'assets/previews/war-survival-v2.webm',
    image: 'assets/images/war-survival-wide.webp',
    thumbnail: 'assets/images/war-survival-card.webp',
    alt: 'War: Survival artwork: blue-armored defenders face a giant red warrior on a bridge above jungle waterfalls.',
    imageLabel: 'Project artwork',
    previewLabel: 'Gameplay highlights · 19s',
    tags: ['Three.js', 'JavaScript', 'Responsive play'],
    facts: [
      ['15', 'campaign sectors'],
      ['3', 'tactical lanes'],
      ['1', 'growing squad'],
    ],
    hook: 'Quick decisions. Growing firepower. A campaign that keeps changing the scenery.',
    challenge:
      'Make recruiting, combat, and upgrades legible at a glance while moving through a fast, visually varied 3D campaign.',
    craft:
      'Three lanes turn movement into strategy. Distinct sector guardians, procedural scenery, touch controls, and persistent campaign progress support short sessions with a longer arc.',
    notice: 'Artwork introduces the world; the preview shows the actual browser game.',
  },
  {
    id: 'rex-encounter',
    title: 'Rex Encounter',
    edition: 'Rex: Pursuit',
    category: 'games',
    type: 'Cinematic chase',
    platform: 'Browser game',
    color: '#d8ba75',
    headline: '90 seconds.\nNo second chances.',
    description:
      'One open Jeep. One mounted gun. One very persistent T. rex. A creature study turned full-throttle chase.',
    url: 'https://vibecodingmatt.github.io/rex-pursuit/',
    source: 'https://github.com/vibecodingmatt/rex-pursuit',
    action: 'Survive the chase',
    preview: 'assets/previews/rex-encounter-v3.webm',
    image: 'assets/images/rex-pursuit-keyart-v2-wide.webp',
    thumbnail: 'assets/images/rex-pursuit-keyart-v2-card.webp',
    alt: 'Rex: Pursuit artwork: a towering T. rex chases an open Jeep and its rear gunner through a sunlit jungle.',
    imageLabel: 'Project artwork',
    previewLabel: 'Chase highlights · 18s',
    tags: ['Three.js', 'Character animation', 'Web Audio'],
    facts: [
      ['90s', 'to survive'],
      ['2', 'camera modes'],
      ['3D', 'animated creature'],
    ],
    hook: 'An up-close creature encounter with nowhere to hide.',
    challenge:
      'Make a giant animated creature feel present, responsive, and threatening inside a browser-sized experience.',
    craft:
      'A living rainforest, tropical storms, layered creature animation, and a working mounted gun bring the pursuit to life. First-person and external cameras share the chase, with persistent battle damage and flashlight-lit night encounters.',
    notice:
      'Rex Encounter is published as Rex: Pursuit. Promotional artwork introduces the chase; the preview shows the actual browser game.',
  },
  {
    id: 'approach-orlando',
    title: 'Approach Orlando',
    edition: '',
    category: 'worlds',
    type: 'Living airport miniature',
    platform: 'Interactive world',
    color: '#9dc9c3',
    headline: 'A whole airport.\nA different perspective.',
    description:
      'Follow a flight, ride the trams, or lean in a little closer. Orlando International, brought to life in miniature.',
    url: 'https://vibecodingmatt.github.io/approach-orlando/',
    source: 'https://github.com/vibecodingmatt/approach-orlando',
    action: 'Explore the airport',
    preview: 'assets/previews/approach-orlando-v3.webm',
    image: 'assets/images/approach-orlando-wide.webp',
    thumbnail: 'assets/images/approach-orlando-card.webp',
    alt: 'Approach Orlando key art: an illuminated model airport in a room overlooking a Florida sunset.',
    imageLabel: 'Project artwork',
    previewLabel: 'Miniature in motion · 18s',
    tags: ['Three.js', 'Geospatial data', 'Simulation'],
    facts: [
      ['4', 'mapped runways'],
      ['114', 'mapped gates'],
      ['1:650', 'miniature scale'],
    ],
    hook: 'A slower kind of play: a place to explore, observe, and get pleasantly lost.',
    challenge:
      'Turn a complex real-world airport into an inviting miniature that rewards both the wide view and a closer look.',
    craft:
      'Mapped airfield geometry, animated aircraft, gate turnarounds, terminal trams, and Florida scenery share a navigable 3D world. Graphics budgets and touch navigation keep the miniature approachable on mobile.',
    notice:
      'The simulation uses illustrative traffic, not live flights. Artwork introduces the setting; the preview shows the real miniature.',
  },
  {
    id: 'matts-angels',
    title: 'Matt’s Angels',
    edition: '',
    category: 'music',
    type: 'Song & music video',
    platform: 'Music & motion',
    color: '#e9a3ce',
    headline: 'A different kind\nof world-building.',
    description:
      'An original song meets neon-lit anime, animated characters, and a little creative rebellion.',
    url: 'https://www.youtube.com/watch?v=6ZtGgA6IDdE',
    source: null,
    action: 'Watch on YouTube',
    preview: 'assets/previews/matts-angels-v2.webm',
    image: 'assets/images/matts-angels-wide.webp',
    thumbnail: 'assets/images/matts-angels-card.webp',
    alt: 'Matt’s Angels: four anime-styled band members against bright pink neon wings.',
    imageLabel: 'Music video artwork',
    previewLabel: 'Music video montage · 14s',
    tags: ['Creative direction', 'AI animation', 'Remotion'],
    facts: [
      ['Song', 'original music'],
      ['Anime', 'visual language'],
      ['Motion', 'storytelling'],
    ],
    hook: 'A creative detour from interactive worlds into a world set to music.',
    challenge:
      'Give a song a coherent visual identity, with characters and scenes that hold together across an entire music video.',
    craft:
      'A neon synthwave and anime direction connects the storyboard, AI-generated scenes, animation, and lyric timing. Remotion brings the visual layers and song into one composition.',
    notice:
      'The short preview is silent. Open the full music video on YouTube for the song and complete experience.',
  },
];
export const featuredId = 'rex-encounter';
